sudo: required
matrix:
  include:
    - language: python
      python:
        - 3.6
      services:
      - docker
      cache:
        - pip
      install:
        - pip install -r requirements.txt
        - python setup.py install
      before_script:
        - docker pull mongo:4.2-bionic
        - sudo docker run -d --name mongo -t mongo:4.2-bionic
        - sleep 1m
      script:
        - flake8 genocrowd tests --ignore=E501,W504
        - pytest --cov=. -vv

    - language: node_js
      node_js:
        - 8
      install:
        - npm install
      script:
        - ./node_modules/.bin/eslint --config .eslintrc.yml "genocrowd/react/src/**"
