sudo: required
matrix:
  include:
    - language: python
      python:
        - 3.6
      services:
        - docker
      cache:
        - pip
      install:
        - pip install -r requirements.txt
        - python setup.py install
      before_script:
        - docker pull mongo:4.2-bionic
        - docker pull quay.io/gmod/apollo:latest
        - dockerId=$(sudo docker run -d --name mongo -t -p 27017:27017 mongo:4.2-bionic)
        - dockerId=$(sudo docker run -d --name apollo -it -v /jbrowse/root/directory/:/data -v postgres-data:/var/lib/postgresql  -p 8888:8080 quay.io/gmod/apollo:latest)
        - docker cp ./tests/dataset/ apollo:/data/dataset/
        - sleep 1m
        - docker logs $dockerId
      script:
        - flake8 genocrowd tests --ignore=E501,W504
        - pytest --cov=. -vv


    - language: python
      python:
        - 3.7
      services:
        - docker
      cache:
        - pip
      install:
        - pip install -r requirements.txt
        - python setup.py install
      before_script:
        - docker pull mongo:4.2-bionic
        - docker pull quay.io/gmod/apollo:latest
        - dockerId=$(sudo docker run -d --name mongo -t -p 27017:27017 mongo:4.2-bionic)
        - dockerId=$(sudo docker run -d --name apollo -t -p 8888:8080 quay.io/gmod/apollo:latest)
        - docker cp ./tests/dataset/ apollo:/data/dataset/
        - sleep 1m
        - docker logs $dockerId
      script:
        - flake8 genocrowd tests --ignore=E501,W504
        - pytest --cov=. -vv
    - language: node_js
      node_js:
        - 8
      install:
        - npm install
      script:
        - ./node_modules/.bin/eslint --config .eslintrc.yml "genocrowd/react/src/**"
