site_name: Genocrowd
repo_url: https://github.com/annotons/genocrowd
edit_uri: edit/master/docs/
site_author: Anthony Bretaudeau

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - bash
    - python
    - javascript
markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 1


nav:
  - Home: index.md
  - Admin :
    - Deploy Genocrowd: deploy.md
    - Configure: configure.md
  - Developer guide:
    - Contribute: contribute.md
    - Doc: docs.md
  - Bug Tracker: https://github.com/annotons/genocrowd/issues

extra_css: [style.css]
